apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd-control
  name: httpd-control
spec:
  containers:
  - image: httpd
    name: httpd-control
    resources: {}
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
